local-development:
  host: localhost
  database: opcoes_development

development:
  host: piousbox.com
  database: opcoes_development

test:
  host: piousbox.com
  database: opcoes_test

production:
  host: piousbox.com
  database: opcoes_development